version: 2.0

jobs:
  test-output:
    docker:
    - image: circleci/python:2.7-stretch
    steps:
    - checkout
    - run: echo "グーテンモルゲン"
    - run: echo $VERY_TEST_VAR
    - run: sleep 5
    - run: echo "グーテンアーベント. バイバイ, Auf Wiedersehen, アウフヴィーダーゼーエン. ありがとう, Danke schön, ダンケシェーン."

workflows:
  version: 2
  test:
    jobs:
    - test-output




















































































