version: 2.1
executors:
  gcloud:
    docker:
    - image: google/cloud-sdk:latest

jobs:
  build:
    executor: gcloud
    steps:
      - run: echo testt

workflows:
  version: 2
  build:
    jobs:
    - build
