version: 2.1

orbs:
  foo: yundt/foo@dev:jp_text

jobs:
  test-jp-text:
    docker:
    - image: circleci/python:2.7-stretch
    steps:
    - foo/hello


workflows:
  version: 2
  test:
    jobs:
    - test-jp-text
