version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
  test:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
workflows:
  version: 2

  build_and_test:
    jobs:
      - build:
          requires:
            - test
      - test:
          requires:
            - build
