version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
  build:
    machine: true
    steps:
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        requires:
          - test
      - test:
        requires:
          - build
