version: 2.1
executors:
  gcloud:
    docker:
    - image: google/cloud-sdk:latest
jobs:
  gcloud_auth_and_configure_docker:
    docker:
    - image: google/cloud-sdk:latest
    steps:
    - setup_remote_docker
    - run: echo test
  build_container_image:
      executor: gcloud
      steps:
          - run: echo test
workflows:
  version: 2
  push_to_gcr:
    jobs:
    - gcloud_auth_and_configure_docker
    - build_container_image
