version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          type: unknown
      - test:
          requires:
            - build
